/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmad
 */
public class FORM_EDIT_BARANG extends javax.swing.JFrame {
    private DefaultTableModel DftTblModel_barang;
    private String SQL;

    /**
     * Creates new form FORM_EDIT_BARANG
     */
    public FORM_EDIT_BARANG() {
        initComponents();
        this.awal();
        this.TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. gThe content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_barang = new javax.swing.JTable();
        jTextField_kode_barang = new javax.swing.JTextField();
        jComboBox_satuan = new javax.swing.JComboBox<>();
        jTextField_nama_barang = new javax.swing.JTextField();
        jButton_edit = new javax.swing.JButton();
        jTextField_harga = new javax.swing.JTextField();
        jTextField_stok = new javax.swing.JTextField();
        jButton_batal = new javax.swing.JButton();
        jButton_keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_cari = new javax.swing.JTextField();
        jButton_cari = new javax.swing.JButton();
        jButton_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode_Barang", "nama_barang", "harga", "satuan", "stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_barang);

        jTextField_kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_kode_barangActionPerformed(evt);
            }
        });

        jComboBox_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satuan", "Unit", "Lusin", "Box", " " }));
        jComboBox_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_satuanActionPerformed(evt);
            }
        });

        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jTextField_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stokActionPerformed(evt);
            }
        });

        jButton_batal.setText("Batal");
        jButton_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_batalActionPerformed(evt);
            }
        });

        jButton_keluar.setText("Keluar");
        jButton_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_keluarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("EDIT DATA BARANG");

        jLabel2.setText("Kode Barang");

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Harga");

        jLabel5.setText("Satuan");

        jLabel6.setText("Stok");

        jLabel7.setText("Masukkan Kode Barang");

        jButton_cari.setText("Cari");
        jButton_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cariActionPerformed(evt);
            }
        });

        jButton_kembali.setText("Kembali");
        jButton_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_cari)
                        .addGap(60, 60, 60))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_edit))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_batal)
                                .addGap(27, 27, 27)
                                .addComponent(jButton_keluar)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_kembali))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_kode_barang)
                                .addComponent(jTextField_nama_barang)
                                .addComponent(jTextField_harga, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(jComboBox_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cari))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_kode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_edit)
                    .addComponent(jButton_batal)
                    .addComponent(jButton_keluar)
                    .addComponent(jButton_kembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_satuanActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stat = conn.prepareStatement(
            "update barang set nama_barang=?, harga=?, satuan =?, stok =? where kode_barang =?");
            stat.setString(1, jTextField_nama_barang.getText());
            stat.setString(2, jTextField_harga.getText());
            stat.setString(3, jComboBox_satuan.getSelectedItem().toString());
            stat.setString(4, jTextField_stok.getText());
            stat.setString(5, jTextField_kode_barang.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit", "pesan",
                    JOptionPane.INFORMATION_MESSAGE);
            hapusData();
            TampilData();
            this.awal();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data tidak berhasil disimpan" + e, "pesan",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jTextField_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stokActionPerformed

    private void jButton_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_batalActionPerformed
        // TODO add your handling code here:
       jButton_cari.setEnabled(true);
       jButton_batal.setEnabled(false);
    }//GEN-LAST:event_jButton_batalActionPerformed

    public void TampilData() {
        DftTblModel_barang = new DefaultTableModel ();
        DftTblModel_barang.addColumn ("KODE BARANG");
        DftTblModel_barang.addColumn ("NAMA BARANG");
        DftTblModel_barang.addColumn ("HARGA");
        DftTblModel_barang.addColumn ("SATUAN");
        DftTblModel_barang.addColumn ("STOK");
        
        jTable_barang.setModel (DftTblModel_barang);
        Connection conn = Koneksi.getConnection();
        try {
             java.sql.Statement stat = conn.createStatement();
             SQL = "select * from barang";
             java.sql.ResultSet res = stat.executeQuery(SQL);
             while (res.next()){
        DftTblModel_barang.addRow(new Object[]{
        res.getString("kode_barang"),
        res.getString("nama_barang"),
        res.getString("harga"),
        res.getString("satuan"),
        res.getString("stok")
     });
  }
         jTable_barang.requestFocus(); 
    } catch (SQLException e) {
        System.out.println(e.getMessage()); 
        }
    }
    
    public void hapusData() {
    jTextField_kode_barang.setText ("");
    jTextField_nama_barang.setText("");
    jTextField_harga.setText("");
    this.combobox();
    jTextField_stok.setText ("");
    }
    
    public void awal() {
    jTextField_kode_barang.setEnabled(false);
    jTextField_nama_barang.setEnabled(false);
    jTextField_harga.setEnabled(false);
    jComboBox_satuan.setEnabled(false);
    jTextField_stok.setEnabled (false);
    }
    
    public void aktif() {
    jTextField_kode_barang.setEnabled(true);
    jTextField_nama_barang.setEnabled(true);
    jTextField_harga.setEnabled(true);
    jComboBox_satuan.setEnabled(true);
    jTextField_stok.setEnabled (true);
}

    public void combobox () {
    jComboBox_satuan.removeAllItems();
    jComboBox_satuan.addItem("Pilih Satuan");
    jComboBox_satuan.addItem("Unit");
    jComboBox_satuan.addItem("Lusin");
    jComboBox_satuan.addItem("Box");
}

    private void jButton_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_keluarActionPerformed

    private void jTextField_kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_kode_barangActionPerformed

    private void jButton_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cariActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        try {
            PreparedStatement stat = conn.prepareStatement("select * from barang where kode_barang = ?");
            stat.setString(1, jTextField_cari.getText());
            ResultSet resultSet = stat.executeQuery();
            if (resultSet.next()) {
                jTextField_kode_barang.setText(resultSet.getString("kode_barang"));
                jTextField_nama_barang.setText(resultSet.getString("nama_barang"));
                
                for (int i = 0; i < jComboBox_satuan.getItemCount(); i++) {
                    if (jComboBox_satuan.getItemAt(i).equals(resultSet.getString("satuan"))) {
                        jComboBox_satuan.setSelectedIndex(1);
                    }
                }
                
                jTextField_harga.setText(resultSet.getString("harga"));
                jTextField_stok.setText(resultSet.getString("stok"));
                jButton_edit.setEnabled(true);
                this.aktif();
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton_cariActionPerformed

    private void jTable_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_barangMouseClicked
        // TODO add your handling code here:
         int baris = jTable_barang.getSelectedRow();

    jTextField_kode_barang.setText(
        DftTblModel_barang.getValueAt(baris, 0).toString()
    );
    jTextField_nama_barang.setText(
        DftTblModel_barang.getValueAt(baris, 1).toString()
    );
    jTextField_harga.setText(
        DftTblModel_barang.getValueAt(baris, 2).toString()
    );

    for (int i = 0; i < jComboBox_satuan.getItemCount(); i++) {
        if (jComboBox_satuan.getItemAt(i)
            .equals(DftTblModel_barang.getValueAt(baris, 3).toString())) {
            jComboBox_satuan.setSelectedIndex(i);
        }
    }

    jTextField_stok.setText(
        DftTblModel_barang.getValueAt(baris, 4).toString()
    );

    aktif(); // biar langsung bisa diedit
    }//GEN-LAST:event_jTable_barangMouseClicked

    private void jButton_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kembaliActionPerformed
        // TODO add your handling code here:
        new FORM_MENU().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_kembaliActionPerformed

  
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_EDIT_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_EDIT_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_EDIT_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_EDIT_BARANG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_EDIT_BARANG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_batal;
    private javax.swing.JButton jButton_cari;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_keluar;
    private javax.swing.JButton jButton_kembali;
    private javax.swing.JComboBox<String> jComboBox_satuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_barang;
    private javax.swing.JTextField jTextField_cari;
    private javax.swing.JTextField jTextField_harga;
    private javax.swing.JTextField jTextField_kode_barang;
    private javax.swing.JTextField jTextField_nama_barang;
    private javax.swing.JTextField jTextField_stok;
    // End of variables declaration//GEN-END:variables
}
