/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmad
 */
public class FORM_TRANSAKSI extends javax.swing.JFrame {

    DefaultTableModel model;
    /**
     * Creates new form FORM_TRANSAKSI
     */
    public FORM_TRANSAKSI() {
     initComponents();
     model = new DefaultTableModel();
     model.addColumn("Kode");
     model.addColumn("Nama");
     model.addColumn("Harga");
     model.addColumn("Jumlah");
     model.addColumn("Subtotal");
     jTable_transaksi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_cari = new javax.swing.JTextField();
        jButton_cari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_kodebarang = new javax.swing.JTextField();
        jTextField_namabarang = new javax.swing.JTextField();
        jTextField_harga = new javax.swing.JTextField();
        jComboBox_satuan = new javax.swing.JComboBox<>();
        jTextField_stok = new javax.swing.JTextField();
        jTextField_jumlahbeli = new javax.swing.JTextField();
        jButton_keranjangbeli = new javax.swing.JButton();
        jButton_batal = new javax.swing.JButton();
        jButton_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_transaksi = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_pembayaran = new javax.swing.JTextField();
        jTextField_kembalian = new javax.swing.JTextField();
        jButton_bayar = new javax.swing.JButton();
        jButton_kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("TRANSAKSI PENJUALAN BARANG");

        jLabel2.setText("MASUKKAN KODE BARANG");

        jButton_cari.setText("CARI");
        jButton_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cariActionPerformed(evt);
            }
        });

        jLabel3.setText("Kode Barang");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Harga");

        jLabel6.setText("Satuan");

        jLabel7.setText("Stok");

        jLabel8.setText("Jumlah Beli");

        jComboBox_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unit", "Lusin", "Box" }));
        jComboBox_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_satuanActionPerformed(evt);
            }
        });

        jButton_keranjangbeli.setText("Keranjang Beli");
        jButton_keranjangbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_keranjangbeliActionPerformed(evt);
            }
        });

        jButton_batal.setText("Batal");

        jButton_keluar.setText("Keluar");

        jTable_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KODE BARANG", "NAMA BARANG", "HARGA", "SATUAN", "STOK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_transaksi);

        jLabel9.setText("TOTAL HARGA");

        jLabel10.setText("Masukkan Uang Pembayaran");

        jLabel11.setText("Kembalian");

        jTextField_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_kembalianActionPerformed(evt);
            }
        });

        jButton_bayar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_bayar.setText("PROSES BAYAR");
        jButton_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bayarActionPerformed(evt);
            }
        });

        jButton_kembali.setText("Kembali");
        jButton_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jButton_keranjangbeli))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton_batal)
                                            .addComponent(jTextField_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_keluar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton_kembali))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jTextField_kembalian)))
                            .addComponent(jButton_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_cari)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cari))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_keranjangbeli)
                    .addComponent(jButton_batal)
                    .addComponent(jButton_keluar)
                    .addComponent(jButton_kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton_bayar)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_keranjangbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_keranjangbeliActionPerformed
        // TODO add your handling code here:
   double harga = Double.parseDouble(jTextField_harga.getText());
double stok  = Double.parseDouble(jTextField_stok.getText());
int jumlah   = Integer.parseInt(jTextField_jumlahbeli.getText());

if (jumlah > stok) {
    JOptionPane.showMessageDialog(this, "Stok tidak cukup");
    return;
}

double subtotal = harga * jumlah;

model.addRow(new Object[]{
    jTextField_kodebarang.getText(),
    jTextField_namabarang.getText(),
    harga,
    jumlah,
    subtotal
});

hitungTotal();


    }//GEN-LAST:event_jButton_keranjangbeliActionPerformed

    private void jTextField_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_kembalianActionPerformed

    private void jButton_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cariActionPerformed
        // TODO add your handling code here:
         Connection conn = Koneksi.getConnection();
    try {
        PreparedStatement ps = conn.prepareStatement(
            "SELECT * FROM barang WHERE kode_barang=?"
        );
        ps.setString(1, jTextField_cari.getText());
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            jTextField_kodebarang.setText(rs.getString("kode_barang"));
            jTextField_namabarang.setText(rs.getString("nama_barang"));
            jTextField_harga.setText(rs.getString("harga"));
            jTextField_stok.setText(rs.getString("stok"));

            for (int i = 0; i < jComboBox_satuan.getItemCount(); i++) {
                if (jComboBox_satuan.getItemAt(i)
                        .equals(rs.getString("satuan"))) {
                    jComboBox_satuan.setSelectedIndex(i);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Barang tidak ditemukan");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    jTextField_kodebarang.setEditable(false);
jTextField_namabarang.setEditable(false);
jTextField_harga.setEditable(false);
jTextField_stok.setEditable(false);
jComboBox_satuan.setEnabled(false);

    }//GEN-LAST:event_jButton_cariActionPerformed

    private void jButton_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bayarActionPerformed
        // TODO add your handling code here:
        double total = Double.parseDouble(jTextField_total.getText());
double bayar = Double.parseDouble(jTextField_pembayaran.getText());

if (bayar < total) {
    JOptionPane.showMessageDialog(this, "Uang bayar kurang!");
    return;
}

double kembalian = bayar - total;
jTextField_kembalian.setText(String.valueOf(kembalian));

      DefaultTableModel model = (DefaultTableModel) jTable_transaksi.getModel();

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Belum ada transaksi");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/pos", "root", ""
        );

        String sql = "UPDATE barang SET stok = stok - ? WHERE kode_barang = ?";
        PreparedStatement pst = conn.prepareStatement(sql);

        for (int i = 0; i < model.getRowCount(); i++) {
            String kodeBarang = model.getValueAt(i, 0).toString();
            int jumlahBeli = Integer.parseInt(model.getValueAt(i, 3).toString());

            pst.setInt(1, jumlahBeli);
            pst.setString(2, kodeBarang);
            pst.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "Pembayaran berhasil");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal update stok: " + e.getMessage());
    }
    resetForm();

    }//GEN-LAST:event_jButton_bayarActionPerformed

    private void jComboBox_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_satuanActionPerformed

    private void jButton_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kembaliActionPerformed
        // TODO add your handling code here:
        new FORM_MENU().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_kembaliActionPerformed

    private void hitungTotal() {
    double total = 0;

for (int i = 0; i < model.getRowCount(); i++) {
    total += Double.parseDouble(
        model.getValueAt(i, 4).toString()
    );
}

jTextField_total.setText(String.valueOf(total));

}
    private void resetForm() {
    // kosongkan textfield
    jTextField_kodebarang.setText("");
    jTextField_namabarang.setText("");
    jTextField_harga.setText("");
    jTextField_stok.setText("");
    jTextField_jumlahbeli.setText("");
    jTextField_total.setText("");
    jTextField_pembayaran.setText("");
    jTextField_kembalian.setText("");
    jTextField_cari.setText("");

    // aktifkan kembali field yang tadi dikunci
    jTextField_kodebarang.setEditable(true);
    jTextField_namabarang.setEditable(false); // kalau pakai cari
    jTextField_harga.setEditable(false);
    jTextField_stok.setEditable(false);

    // kosongkan tabel transaksi
    DefaultTableModel model = (DefaultTableModel) jTable_transaksi.getModel();
    model.setRowCount(0);

    // fokus balik ke kode barang
    jTextField_kodebarang.requestFocus();
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_TRANSAKSI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_batal;
    private javax.swing.JButton jButton_bayar;
    private javax.swing.JButton jButton_cari;
    private javax.swing.JButton jButton_keluar;
    private javax.swing.JButton jButton_kembali;
    private javax.swing.JButton jButton_keranjangbeli;
    private javax.swing.JComboBox<String> jComboBox_satuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_transaksi;
    private javax.swing.JTextField jTextField_cari;
    private javax.swing.JTextField jTextField_harga;
    private javax.swing.JTextField jTextField_jumlahbeli;
    private javax.swing.JTextField jTextField_kembalian;
    private javax.swing.JTextField jTextField_kodebarang;
    private javax.swing.JTextField jTextField_namabarang;
    private javax.swing.JTextField jTextField_pembayaran;
    private javax.swing.JTextField jTextField_stok;
    private javax.swing.JTextField jTextField_total;
    // End of variables declaration//GEN-END:variables
}
