/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

/**
 *
 * @author ahmad
 */
public class FORM_MENU2 extends javax.swing.JFrame {

    /**
     * Creates new form FORM_MENU2
     */
    public FORM_MENU2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu_INPUT = new javax.swing.JMenu();
        jMenu_EDIT = new javax.swing.JMenu();
        jMenu_DELETE = new javax.swing.JMenu();
        jMenu_DISPLAY = new javax.swing.JMenu();
        jMenu_TRANSAKSI = new javax.swing.JMenu();
        jMenu_HISTORY = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenu_INPUT.setForeground(new java.awt.Color(255, 153, 0));
        jMenu_INPUT.setText("INPUT BARANG");
        jMenu_INPUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_INPUTMouseClicked(evt);
            }
        });
        jMenu1.add(jMenu_INPUT);

        jMenu_EDIT.setForeground(new java.awt.Color(255, 153, 51));
        jMenu_EDIT.setText("EDIT BARANG");
        jMenu_EDIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_EDITMouseClicked(evt);
            }
        });
        jMenu1.add(jMenu_EDIT);

        jMenu_DELETE.setForeground(new java.awt.Color(255, 153, 51));
        jMenu_DELETE.setText("DELETE BARANG");
        jMenu_DELETE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_DELETEMouseClicked(evt);
            }
        });
        jMenu1.add(jMenu_DELETE);

        jMenu_DISPLAY.setForeground(new java.awt.Color(255, 153, 51));
        jMenu_DISPLAY.setText("TAMPILKAN BARANG");
        jMenu_DISPLAY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_DISPLAYMouseClicked(evt);
            }
        });
        jMenu1.add(jMenu_DISPLAY);

        jMenu_TRANSAKSI.setForeground(new java.awt.Color(255, 153, 51));
        jMenu_TRANSAKSI.setText("TRANSAKSI");
        jMenu_TRANSAKSI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_TRANSAKSIMouseClicked(evt);
            }
        });
        jMenu1.add(jMenu_TRANSAKSI);

        jMenu_HISTORY.setForeground(new java.awt.Color(255, 153, 51));
        jMenu_HISTORY.setText("RIWAYAT PENJUALAN");
        jMenu_HISTORY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_HISTORYMouseClicked(evt);
            }
        });
        jMenu1.add(jMenu_HISTORY);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_INPUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_INPUTMouseClicked
        // TODO add your handling code here:
         FORM_INPUT_BARANG A = new FORM_INPUT_BARANG();
         A.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenu_INPUTMouseClicked

    private void jMenu_EDITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_EDITMouseClicked
        // TODO add your handling code here:
         FORM_EDIT_BARANG A = new FORM_EDIT_BARANG();
         A.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenu_EDITMouseClicked

    private void jMenu_DELETEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_DELETEMouseClicked
        // TODO add your handling code here:
         FORM_DELETE_DATA A = new FORM_DELETE_DATA();
         A.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenu_DELETEMouseClicked

    private void jMenu_DISPLAYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_DISPLAYMouseClicked
        // TODO add your handling code here:
         FORM_DISPLAY_BARANG A = new FORM_DISPLAY_BARANG();
         A.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenu_DISPLAYMouseClicked

    private void jMenu_TRANSAKSIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_TRANSAKSIMouseClicked
        // TODO add your handling code here:
         FORM_TRANSAKSI A = new FORM_TRANSAKSI();
         A.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenu_TRANSAKSIMouseClicked

    private void jMenu_HISTORYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_HISTORYMouseClicked
        // TODO add your handling code here:
         FORM_HISTORY A = new FORM_HISTORY();
         A.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenu_HISTORYMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_MENU2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_MENU2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_MENU2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_MENU2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_MENU2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_DELETE;
    private javax.swing.JMenu jMenu_DISPLAY;
    private javax.swing.JMenu jMenu_EDIT;
    private javax.swing.JMenu jMenu_HISTORY;
    private javax.swing.JMenu jMenu_INPUT;
    private javax.swing.JMenu jMenu_TRANSAKSI;
    // End of variables declaration//GEN-END:variables
}
